spring.application.name=SEGULAProject
# Configuration du serveur
server.port=8020
# Configuration de la base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/PfeProject?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG


# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Gestion des objets JSON vides
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false



# JSON Web Token (JWT) Secret
#jwt.secret=javainuse
cryptoserver.app.jwtExpiration=1000000
cryptoserver.app.jwtSecret=azerty

google.clientId=YOUR_GOOGLE_CLIENT_ID

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/SEGULAProject-swagger-ui.html


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=farahbouricha98@gmail.com 
spring.mail.password=ghxa zjmk yfns mpbo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuration du stockage des fichiers
file.upload-dir=src/main/resources/uploads


